In [1]:
import numpy as np

'1.13.0'

In [2]:
a = np.array([0, 1, 2, 3, 4, 5])
a

array([0, 1, 2, 3, 4, 5])

In [3]:
# Cuantas dimensiones o ejes tiene el "array"
a.ndim

1

In [4]:
# Cual es la estructura o forma del array y el tamaño en cada dimension.
a.shape

(6,)

In [5]:
# Creamos uno nuevo
b = a.reshape((3,2))
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
b[1][0] = 77
b

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [7]:
# Esto nos muestra que apuntan a los mismos valores.
a

array([ 0,  1, 77,  3,  4,  5])

In [8]:
b.ndim

2

In [9]:
b.shape

(3, 2)

In [10]:
# Si queremos crear una copia a un elemento nuevo
c = a.reshape((3, 2)).copy()
c

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [11]:
c[0][0] = -99
a

array([ 0,  1, 77,  3,  4,  5])

In [12]:
b

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [13]:
c

array([[-99,   1],
       [ 77,   3],
       [  4,   5]])

In [14]:
# Las operaciones se propagan a los elementos constituyentes
a * 2

array([  0,   2, 154,   6,   8,  10])

In [15]:
a ** 2

array([   0,    1, 5929,    9,   16,   25])

In [16]:
# Arrays como indices
a[np.array([2, 3, 4])]

array([77,  3,  4])

In [17]:
# Aprovechando la propagacion de las operaciones
a > 4

array([False, False,  True, False, False,  True], dtype=bool)

In [18]:
a[a > 4]

array([77,  5])

In [19]:
# Incluso para excluir valores marginales.
a[a > 4] = 4
a

array([0, 1, 4, 3, 4, 4])

In [20]:
# Aunque existe un metodo para esto.
a.clip(0, 4)

array([0, 1, 4, 3, 4, 4])